### ISSUE TITLE
Automate manifest generation

### ISSUE THREAD

**Issue by garyburd** [neovim/go-client#1]
Plugin authors generate a [plugin manifest](https://neovim.io/doc/user/remote_plugin.html#remote-plugin-manifest) using the following steps:
1. Build the plugin application using `go`, `gb` or some other development tool.
2. Run the application with the `--manifest=hostName` command line flag to print a manifest.
3. Add the the manifest to a .vim file ([example)](https://github.com/garyburd/vigor/blob/master/plugin/vigor.vim).

These steps must be repeated every time the plugin handler registrations are changed.

This process should be automated in some way. Possible options are:
- Modify the plugin application to update a .vim file directly instead of printing the manifest to stdout.
- Create a [`go generate`](https://blog.golang.org/generate) tool for updating manifests.
- Modify :UpdateRemotePlugins to work with compiled executables.

**Comment by garyburd** [comment]
Here's one possible workflow for users:

1. User adds the plugin binary to $PATH.  The `go get` command is one way to do this. 
1. User adds line to init.vim to register binary:  `remote#host#RegisterExecutable('mycommand')`
1. User runs :UpdateRemotePlugins

This workflow requires the addition of `RegisterExecutable` and modification of `remote#host#UpdateRemotePlugins`.

**Comment by justinmk** [comment]
was this addressed by https://github.com/neovim/go-client/pull/25 ?

**Comment by justinmk** [comment]
Remote plugin "manifest" will be removed (and not supported) after https://github.com/neovim/neovim/issues/27949 is implemented.
