### ISSUE TITLE
ExecLua function will cause neovim hangup

### ISSUE THREAD

**Issue by glepnir** [neovim/go-client#104]
@zchee   I can confirm my lua code can works well. 

```go
func (c *Command) LspInstall(p *plugin.Plugin) ([]string, error) {
	userConfig := make([]string, 0)
	getUserConfig := "require('lspmeta').get_user_config_server()"
	if err := c.nvim.ExecLua(getUserConfig, userConfig); err != nil {
		return nil, err
	}
	return userConfig, nil
}
```

 lua code 
```lua
function lspmeta.get_user_config_server()
  local lspconfig = npcall(require,'lspconfig')
  if not lspconfig then
    -- check the packer exist
    if next(packer_plugins) ~= nil then
      vim.cmd [[packadd nvim-lspconfig]]
      lspconfig = require('lspconfig')
    else
      return
    end
  end

  local configs = require('lspconfig/configs')
  return vim.tbl_keys(configs)
end
```

**Comment by zchee** [comment]
@glepnir Thanks! will check it.

**Comment by glepnir** [comment]
take code form test file. also hangup.

![Untitled](https://user-images.githubusercontent.com/41671631/110629616-50e7f100-81df-11eb-916c-ba7e5f0b5941.gif)

**Comment by glepnir** [comment]
any update for thiss issue?

**Comment by zchee** [comment]
@glepnir I'd dig this issue but not yet solved...

**Comment by zchee** [comment]
@glepnir Could you post Go side minimal code?

It's doesn't work at least my local.
```go
func (c *Command) LspInstall(p *plugin.Plugin) ([]string, error) {
	userConfig := make([]string, 0)
	getUserConfig := "require('lspmeta').get_user_config_server()"
	if err := c.nvim.ExecLua(getUserConfig, userConfig); err != nil {
		return nil, err
	}
	return userConfig, nil
}
```

**Comment by glepnir** [comment]
hmm it can't work for you because you does not have lua function right?   check my second image. it use the go test code from `go-client`

**Comment by 9Y5** [comment]
Hi @glepnir @zchee I was facing a similar issue and found out that the issue was due to the `--embed` flag not being set. 

An small lua example is:
```go
func hello(args []string) (int, error) {
	nv, err := nvim.NewChildProcess(
                 ChildProcessArgs("--embed")
        )
	if err != nil {
		return 0, err
	}

	var result int
	program := "local a, b = ... return a + b"

	if err := nv.ExecLua(program, &result, 1, 2); err != nil {
		return result, err
	}

	return result, nil
}

func main() {
	plugin.Main(func(p *plugin.Plugin) error {
		p.HandleFunction(&plugin.FunctionOptions{Name: "Hello"}, hello)
		return nil
	})
}
```

I noticed that there was another issue #155 where it's not obvious that the error is caused by not setting the `--embed` flag. So one way to fix this is to set `--embed` flag always. I've done so in this MR #161 , and allowed users to overwrite this behavior with another option.

Please help review and let me know wdyt about the solution. Thanks
