### ISSUE TITLE
question: Use Batch API without race condition

### ISSUE THREAD

**Issue by zchee** [neovim/go-client#14]
Hi,
Sorry, not issue. just question.

Recently, I tried solved `nvim-go` race conditions. Now, `nvim-go` is super data racy.
I know `nvim-go` complexly and ugly. When I start the develop `nvim-go`, I did not have enough knowledge, and I had priority to the implementation of each command.

BTW, `nvim-go` all commands always uses the goroutine because blocking user UI if without goroutine.
And, Now behavior is `*nvim.Nvim`(and `*nvim.Batch`) is stored in `Command` struct; all commands use the same thing. Because omit `NewBatch()` in each command.

In this case, If another command is executed before any command ends(e.g., execute `GoGuruDefinition`(`nvim-go/commands.(*Commands).Guru()`) twice on 1 sec), `nvim.Batch` will occur data race in go-client internal. (correct?)
So, If I want to use the `Batch` with goroutine, Should I get the lock(or any "wait" way), or always use different `*nvim.{Nvim,Batch}`? (but I do not understand what it will solve)
Or, Is there another way?
Just in case, I know `p.HandleCommand` provide `*nvim.Nvim` variable to first args of function and it's optional.
https://github.com/garyburd/vigor/blob/544a11eb60ac0b5d73a6487ec1944443aa129675/src/format/format.go#L27

The error log is here: (execute `GoGuruDefinition` twice on 1 sec)

```sh
WARNING: DATA RACE
Read at 0x00c4202da0e0 by goroutine 8:
  bytes.(*Buffer).grow()
      /usr/local/go/src/bytes/buffer.go:66 +0x7c
  bytes.(*Buffer).Write()
      /usr/local/go/src/bytes/buffer.go:146 +0x60
  github.com/neovim/go-client/msgpack.(*Encoder).packArrayMapLen()
      /Users/zchee/go/src/github.com/zchee/nvim-go/vendor/src/github.com/neovim/go-client/msgpack/pack.go:187 +0x1a7
  github.com/neovim/go-client/msgpack.(*Encoder).PackArrayLen()
      /Users/zchee/go/src/github.com/zchee/nvim-go/vendor/src/github.com/neovim/go-client/msgpack/pack.go:194 +0x7d
  github.com/neovim/go-client/nvim.(*Batch).call()
      /Users/zchee/go/src/github.com/zchee/nvim-go/vendor/src/github.com/neovim/go-client/nvim/nvim.go:307 +0x41c
  github.com/neovim/go-client/nvim.(*Batch).CurrentBuffer()
      /Users/zchee/go/src/github.com/zchee/nvim-go/vendor/src/github.com/neovim/go-client/nvim/apiimp.go:820 +0x8c
  nvim-go/commands.(*Commands).Guru()
      /Users/zchee/go/src/github.com/zchee/nvim-go/src/nvim-go/commands/guru.go:82 +0x323
  nvim-go/commands.(*Commands).funcGuru.func1()
      /Users/zchee/go/src/github.com/zchee/nvim-go/src/nvim-go/commands/guru.go:47 +0x6a

Previous write at 0x00c4202da0e0 by goroutine 20:
  [failed to restore the stack]

Goroutine 8 (running) created at:
  nvim-go/commands.(*Commands).funcGuru()
      /Users/zchee/go/src/github.com/zchee/nvim-go/src/nvim-go/commands/guru.go:46 +0x74
  nvim-go/commands.(*Commands).(nvim-go/commands.funcGuru)-fm()
      /Users/zchee/go/src/github.com/zchee/nvim-go/src/nvim-go/commands/commands.go:37 +0x69
  runtime.call32()
      /usr/local/go/src/runtime/asm_amd64.s:492 +0x3a
  reflect.Value.Call()
      /usr/local/go/src/reflect/value.go:302 +0xc0
  reflect.(Value).Call-fm()
      /Users/zchee/go/src/github.com/zchee/nvim-go/vendor/src/github.com/neovim/go-client/msgpack/rpc/endpoint.go:521 +0xc3
  github.com/neovim/go-client/msgpack/rpc.(*Endpoint).runNotifications()
      /Users/zchee/go/src/github.com/zchee/nvim-go/vendor/src/github.com/neovim/go-client/msgpack/rpc/endpoint.go:635 +0x15a

Goroutine 20 (running) created at:
  nvim-go/commands.(*Commands).funcGuru()
      /Users/zchee/go/src/github.com/zchee/nvim-go/src/nvim-go/commands/guru.go:46 +0x74
  nvim-go/commands.(*Commands).(nvim-go/commands.funcGuru)-fm()
      /Users/zchee/go/src/github.com/zchee/nvim-go/src/nvim-go/commands/commands.go:37 +0x69
  runtime.call32()
      /usr/local/go/src/runtime/asm_amd64.s:492 +0x3a
  reflect.Value.Call()
      /usr/local/go/src/reflect/value.go:302 +0xc0
  reflect.(Value).Call-fm()
      /Users/zchee/go/src/github.com/zchee/nvim-go/vendor/src/github.com/neovim/go-client/msgpack/rpc/endpoint.go:521 +0xc3
  github.com/neovim/go-client/msgpack/rpc.(*Endpoint).runNotifications()
      /Users/zchee/go/src/github.com/zchee/nvim-go/vendor/src/github.com/neovim/go-client/msgpack/rpc/endpoint.go:635 +0x15a
==================
```

Sorry if my interpretation was wrong.
I would appreciate it if you could answer my questions. Thanks.

**Comment by garyburd** [comment]
The nvim.Nvim type supports concurrent calls. The nvim.Batch and the now deleted nvim.Pipleline types do not support concurrent calls.

The application should create Batch objects as needed. Do not cache the Batch objects.

If we find that the allocations for Batch objects are a problem (and I don't think we will), I can use sync.Pool internally to reduce the allocating.

**Comment by zchee** [comment]
@garyburd Thanks, that's the perfect answer. My doubt was resolved.
I understood the need to assign `nvim.Batch`.

> If we find that the allocations for Batch objects are a problem (and I don't think we will), I can use sync.Pool internally to reduce the allocating.

Sorry confused, I think that the implementation is perfect. Just my interpretation was mistaken.
Deleted `nvim.Pipeline`, `nvim.Batch`, that code are the very good reference for me. I’ve learned a lot from that.

Thank you for your polite answer!
Close.
