### ISSUE TITLE
All api calls blocked if init.vim has syntax errors

### ISSUE THREAD

**Issue by hismailbulut** [neovim/go-client#140]
After connected to neovim as GUI, I could not call any api functions like SetApiInfo if there is a syntax error. If I call it concurrently only goroutine waits and program continues but some of the calls like TryResizeUI responses visibly late (grid_resize)
Before you ask my client has another handler and users can set client options with some set of commands. Users be able to set this options via init.vim and I have to resize the grid at this time, after the first flush but before showing the window.

**Comment by justinmk** [comment]
> After connected to neovim as GUI,

when reporting an issue please provide exact steps. `nvim --embed` explains the way to start Nvim while avoiding the issue you have reported. If that doesn't work for some reason, say exactly what you tried and what happened.

**Comment by hismailbulut** [comment]
After I read docs again I understand that my configuration system is complicated and I understand why so many gui clients uses their own config file. Thanks.
