### ISSUE TITLE
docs: instructions for adding a plugin to Nvim with Lua

### ISSUE THREAD

**Issue by m-kovalevsky** [neovim/go-client#168]
There is an example of writing a plugin which adds Hello command to Nvim

On the step 3 "Add the following plugin to Nvim:" there is a code example written in Vimscript instead of Lua.

It would be great to have the same example but written in Lua.

Ideally, an example can be extended to have more details for developers who never work with go-client and plugin system before. Specifically, it would be great to give more details on the step "Add the following plugin to Nvim" since it does not clarify where exactly do we need to add plugin (what file, folder, etc. and how to register plugin so Neovim will launch it).

**Comment by justinmk** [comment]
> It would be great to have the same example but written in Lua.

sure, that's an easy enough change to make.

> Ideally, an example can be extended to have more details for developers who never work with go-client and plugin system before. Specifically, it would be great to give more details on the step "Add the following plugin to Nvim"

Probably the best reference is the `_test.go` examples in https://github.com/neovim/go-client/tree/main/nvim/plugin 

Long-term (hopefully before end of 2024), the answer is to vastly simplify "remote plugins" as outlined in  https://github.com/neovim/go-client/issues/167

**Comment by justinmk** [comment]
Can you try the steps [outlined here](https://github.com/neovim/go-client/issues/167#issuecomment-2106427175) and report your experience here?

**Comment by garyburd** [comment]
I posted an example of a plugin written in Lua calling functions written in Go.  [Example](https://github.com/neovim/go-client/tree/main/examples/remote).
