### ISSUE TITLE
interface{} -> any

### ISSUE THREAD

**Issue by garyburd** [neovim/go-client#176]
Replace uses of `interface{}` in the code with the alias `any`. 

Steps: 

1. Run `gofmt -w -s .` at the root of the project.
2. Hand edit comments and string literals to replace `interface{}` with `any`.  The templates in nvim/api_tool.go are a notable example of where hand editing is required.
3. Run `go generate`.

This change can create merge conflicts for work in progress.  Should this change wait on any work in progress?

**Comment by justinmk** [comment]
> Should this change wait on any work in progress?

The only non-trivial open PR is https://github.com/neovim/go-client/pull/95 and it doesn't look like it will be hard to adapt to this change. @zchee

**Comment by zchee** [comment]
@garyburd go ahead to will conflicts change. I can following your (repository) upstream change anytime
