### ISSUE TITLE
nvim.NewEmbedded doesn't work on Windows

### ISSUE THREAD

**Issue by dzhou121** [neovim/go-client#20]
When I run ```nvim.NewEmbedded``` on windows, it will error out at ```os.StartProcess```, and if I change to use ```exec.Command```, it works fine.

**Comment by garyburd** [comment]
I use StartProcess to avoid a race.  

What is the specific error returned returned from `nvim.NewEmbedded`?

Show the code that does work for you.

**Comment by dzhou121** [comment]
at [this line](https://github.com/neovim/go-client/blob/master/nvim/nvim.go#L155)

I change

```
c.p, err = os.StartProcess(path,
		append([]string{path, "--embed"}, options.Args...),
		&os.ProcAttr{
			Env:   options.Env,
			Files: []*os.File{inr, outw},
		})
```
into

```
cmd := exec.Command(path, append([]string{path, "--embed"}, options.Args...)...)
cmd.Stdin = inr
cmd.Stdout = outw
err = cmd.Start()
```

**Comment by garyburd** [comment]
What is the error returned returned from nvim.NewEmbedded?

**Comment by dzhou121** [comment]
The error returned by ```os.StartProcess``` is

```fork/exec nvim.exe: invalid argument```

nvim.exe is under the same folder.

**Comment by garyburd** [comment]
Does a7b6ec8bb6a952b6cbeb9ca1d5d6ba73888efc62 fix the problem?

**Comment by dzhou121** [comment]
It's fixed.

Thank you for your help.
