### ISSUE TITLE
Command not found in neovim

### ISSUE THREAD

**Issue by jimmiebtlr** [neovim/go-client#23]
I'm trying to run the hello world, but having trouble following/getting it setup correctly.  UpdateRemotePlugin doesn't appear to be picking it up, and adding the generated lines exactly as is in the readme doesn't seem to have any affect either.

**Comment by garyburd** [comment]
UpdateRemotePlugins is no needed. Try the following to debug the issue:

- Confirm that the compiled Go program is on your PATH by running `hello --help`.  The program prints a usage message when the --help flag is specified.
- Confirm that the plugin is loaded by running the `:scriptnames` commandin nvim.
- Execute the function using the plugin function using `:echo Hello('world')`.  This should echo `hello world`.

**Comment by jimmiebtlr** [comment]
Think that got me closer.

Now have `hello --help` in path when starting neovim.
scriptnames includes the init.vim

Running  `:echo Hello('world')`  gives

```
Error detected while processing function Hello:
line    1:
E475: Invalid argument: Channel id must be a positive integer
0
```

**Comment by jimmiebtlr** [comment]
Should I have something in `$runtimepath/rplugin/hello`?

And if so, should it show up in `:scriptnames` output?

**Comment by garyburd** [comment]
There's was an error in the README file.  The `s:Requirehello` function should be:

```
function! s:Requirehello(host) abort
  return jobstart(['hello'], {'rpc': v:true})
endfunction
```

**Comment by jimmiebtlr** [comment]
That did it!  Thanks
