### ISSUE TITLE
New maintainer needed

### ISSUE THREAD

**Issue by garyburd** [neovim/go-client#38]
I am stepping down as maintainer of this project.  I will do my best to help out until a new maintainer is found.

**Comment by zchee** [comment]
Hmm... I want to assign a new maintainer, but I haven't yet reviewed skill set. :(

**Comment by justinmk** [comment]
Perhaps @zchee and @dzhou121 could continue.

@garyburd Thanks for building a well-designed foundation!

**Comment by zchee** [comment]
@justinmk yep, I still develop [zchee/nvim-go](https://github.com/zchee/nvim-go), So I can continue to maintain this repository.
If @guryburd approve, I can maintain and follows neovim’s new API into this client.

**Comment by zchee** [comment]
@garyburd @justinmk Thanks! I was approved to an invitation. I try as much as I can.

**Comment by zchee** [comment]
@garyburd 
> The golang team has admin rights on the repo, but I do not have permission to change the membership of that team.

It means this team?
![screen shot 2018-09-27 at 13 56 38](https://user-images.githubusercontent.com/6366270/46124125-3c0c8280-c25d-11e8-8a6b-a879f49a35c7.png)

If so, @justinmk can invite to `golang` team to me...?

**Comment by justinmk** [comment]
> can invite to golang team to me.

done

**Comment by zchee** [comment]
@justinmk Ready to close?
