### ISSUE TITLE
Change CI SaaS to CircleCI

### ISSUE THREAD

**Issue by zchee** [neovim/go-client#39]
Now, Travis CI is de-fact SaaS CI. But recently, CircleCI also useful and some improved for the golang testing environment.
I think would be better to switch to CircleCI, because not job pending, faster run testing or etc.

What do you think about it? AFAIK, my company was a switch to CircleCI, As a result, increase build time to x10~x30.
Also, I have much knowledge of CircleCI features.

**Comment by justinmk** [comment]
Not in favor. 

>  not job pending, faster run testing or etc.
> time to x10~x30.

This repo has 43 commits. Those problems are very, very far away from the highest-leverage tasks that could be worked on here.

Neovim project has ~10 repos. If every repo uses a different CI, that increases friction for little benefit.

**Comment by justinmk** [comment]
A high-leverage task, for example, would be: https://github.com/neovim/go-client/issues/29 .
It's high-leverage because the benefit:cost ratio is very high. 

The benefit:cost ratio of switching CI is very low.

**Comment by zchee** [comment]
@justinmk Ah, actually, I don't like TravisCI pending time. CircleCI is almost haven't pending time. That's why I suggest CircleCI.
For example(Currently, it's failed...), but CircleCI can following tasks.
https://circleci.com/workflow-run/3f29a06e-0b01-45c6-aadf-a632a424559a

But, Neovim org using TravisCI is org spec? If so, I respect it. Feel free to close this issue.

**Comment by justinmk** [comment]
It's not an org spec.  But there should be a good reason to change things. Changing CI has a cost. Is the cost worth the benefit? Is it the highest-leverage task that could be worked on?

**Comment by zchee** [comment]
@justinmk 
Hm, OK.

**Comment by zchee** [comment]
@justinmk 
> It's not an org spec. But there should be a good reason to change things. Changing CI has a cost. Is the cost worth the benefit? Is it the highest-leverage task that could be worked on?

Hm, OK. You're correct.
So, I try to CircleCI setup to my forked https://github.com/zchee/neovim-go-client repository. If you like it, accept it. What this plan?

**Comment by justinmk** [comment]
@zchee What do you think about https://sourcehut.org/ ? We are considering this for Nvim core repo as well.

**Comment by justinmk** [comment]
GitHub actions probably makes the most sense for this repo, rather than a third party.

https://github.com/neovim/neovim-ruby/pull/62

**Comment by zchee** [comment]
@justinmk make sense. I'll send PR which use the GitHub action.

**Comment by zchee** [comment]
@justinmk but I didn't repo owner, so can't set secrer env. any idea?

**Comment by justinmk** [comment]
you are on the "golang" team, and all members in that team have "Admin" role on
this repo. There is no "repo owner" role...

can you access this page: https://github.com/neovim/go-client/settings

**Comment by zchee** [comment]
@justinmk Ah! I'd mistaken. I can see that URL.
Thanks :D

**Comment by zchee** [comment]
We switched to GitHub Actions. close.
