### ISSUE TITLE
Need a more detail tutorial .

### ISSUE THREAD

**Issue by glepnir** [neovim/go-client#73]
@zchee  I think we need a more usage tutorial . I want use this lib to write a plugin. but there is only a easy example ..

**Comment by zchee** [comment]
@glepnir okay, I'll write a full example of how to write neovim plugin written in Go.
including https://github.com/neovim/go-client/issues/68#issuecomment-609034423 and #75.

/cc @DenLilleMand

**Comment by glepnir** [comment]
@zchee  That‘s sounds great, I am referring to your` nvim-go` to write the plugin. It is very useful for me.

**Comment by alexaandru** [comment]
+1 from me :) Trying to figure out how can I use signs (set/unset) from Go client as well as how can I read the quickfix list (or rather/better - how can I "subscribe" to it to be notified about changes, without having to re-read it over and over).

I found nothing about sings in the API though: https://neovim.io/doc/user/api.html but I know they are supported since other plugins are using them :) so :shrug:

**Comment by glepnir** [comment]
@alexaandru  For now, you can refer to [nvim-go](https://github.com/zchee/nvim-go) to implement your ideas. Thanks @zchee. [nvim-go](https://github.com/zchee/nvim-go) gave me a lot of inspiration.

**Comment by zchee** [comment]
invited https://github.com/zchee/nvim-lsp
which is almost for me, so internal repo. but might be more helped you

**Comment by zchee** [comment]
FYI:
sign is https://github.com/zchee/nvim-lsp/blob/master/pkg/runtime/sign.go
event is https://github.com/zchee/nvim-lsp/blob/master/pkg/runtime/event.go

**Comment by glepnir** [comment]
@zchee  wow I accepted the invitation, and I will read it tomorrow, hoping to get more used methods.

**Comment by alexaandru** [comment]
Much appreciated all for the pointers and the invite!

**Comment by zchee** [comment]
also
https://github.com/zchee/nvim-lsp/blob/master/pkg/lsp/lsp.go#L112-L133

**Comment by ThreeFx** [comment]
I'm currently also stuck trying to make sense of how `nvim.Subscribe` works.

Where is the callback that I have to register?

**Comment by zchee** [comment]
@ThreeFx okay, I’ll write test code. Maybe it helped you.

**Comment by filmil** [comment]
Hi folks. If you wonder how `nvim.Subscribe` works, or how to use it to get notified of autocmd events, I just figured it out using `go-client`, without the plugin API:

https://github.com/neovim/neovim/discussions/27371

**Comment by justinmk** [comment]
Remote plugins will be greatly simplified by https://github.com/neovim/neovim/issues/27949 , and we will update the docs then.
