### ISSUE TITLE
Example outdated?

### ISSUE THREAD

**Issue by meonlol** [neovim/go-client#9]
I wanted to try the go-client out, but I can't seem to get the basic example from the README.md working. I'm not familiar enough with the process to figure out what is wrong, but the fact that `rpcstart` is now deprecated gives me to think that the example might be outdated.

I've followed the steps described, and the function is created and callable without an error, but I don't seem to get a reply back.

Any ideas what could have gone wrong?

**Comment by garyburd** [comment]
The example works after replacing the text `insert path to executable here` with the path to executable built from the example Go program. Please describe in more detail what you tried.

I'll update the example to use `jobstart`.
